### PR TITLE
Replace icons with emojis

### LINKED ISSUE #85: Replace the limited set of tag icons by emojis
It would be a nice feature to allow to specify a custom icon for a tag.

### PR DESCRIPTION
**Pull request by diegogangl**
Replace the old icons with shiny new emojis. 
Testing appreciated!

closes #85

### CODE REVIEW

**Comment by flavin** [comment]
@diegogangl the emoji popup is cut off in window edge
image

**Comment by diegogangl** [comment]
Yup, this is a limitation of Gtk3 on X11. 
https://gitlab.gnome.org/GNOME/gtk/-/issues/543

Won't be fixed for Gtk3. I tried adding more padding but forgot that other font sizes would also make the popover larger. What we could do as a workaround is to make that window resizable.

**Comment by diegogangl** [comment]
@flavin did you find other issues?

**Comment by flavin** [comment]
@diegogangl only that, other stuff good great

**Pull request merged**
