### PR TITLE
test with more recent python versions and use sudo:false

### PR DESCRIPTION
**Pull request by tomspur**
With sudo:false, travis can use [containers](http://docs.travis-ci.com/user/workers/container-based-infrastructure/) and has a faster startup time.

### CODE REVIEW

**Comment by tomspur** [comment]
Unfortunately, `gir1.2-networkmanager-1.0` cannot be installed yet and needs an [approval](https://github.com/travis-ci/apt-package-whitelist#package-approval-process). So maybe the old way of running the tests is just fine and this can be revisited, if the containers have a bigger advantage to the current way of running tests...

**Comment by izidormatusov** [comment]
Can you file a bug for approval of that package in meanwhile? You could
then reopen PA after it is added

**Comment by tomspur** [comment]
The whitelist requst is at travis-ci/travis-ci#3895 now. I don't think it is save to add that package in the container environment, but we'll see...

**Comment by izidormatusov** [comment]
Other possibility is to make network manager as an optional dependency.
It's nicely isolated in GTG/tools/networkmanager.py and if the dependency
is not available, is_connection_up() fall back to safe *always return True*
.

**Pull request closed without merging**
