### PR TITLE
New file format (testing appreciated)

### LINKED ISSUE #279: Better XML format [RFC]
We can (and _should_) improve the file format of the local backend. A more strict structure would help us move everything into the treemodel faster, and avoid many bugs. 

## Current format

For reference this is what a task currently looks like:

```xml
	<task id="1@1" status="Active" tags="" uuid="d1312d77-d42d-4403-b080-ca065dde166f">
		<title>Learn How To Use Subtasks</title>
		<addeddate>2020-04-10T20:48:11</addeddate>
		<modified>2020-04-10T20:37:02</modified>
		<subtask>6000caf7-6197-4d77-a50e-8bd8804c5694</subtask>
		<subtask>7ab5f54c-dc3c-4cae-a968-1361d7269eb6</subtask>
		<subtask>3749c090-0d84-48b5-ad85-941657c3cff9</subtask>
		<content>A &amp;quot;Subtask&amp;quot; is something that you need to do first before being able to accomplish your task. In GTG, the purpose of subtasks is to cut down a task in smaller subtasks that are easier to achieve and to track down.

To insert a subtask in the task description (this window, for instance), begin a line with &amp;quot;-&amp;quot;, then write the subtask title and press Enter.

Try inserting one subtask below. Type &amp;quot;- This is my first subtask!&amp;quot;, for instance, and press Enter:

→   One subtask
→   Another subtask
→   Yet another one



Alternatively, you can also use the &amp;quot;Insert Subtask&amp;quot; button.

Note that subtasks obey to some rules: first, a subtask's due date can never happen after its parent's due date and, second, when you mark a parent task as done, its subtasks will also be marked as done.

And if you are not happy with your current tasks/subtasks organization, you can always change it by drag-and-dropping tasks on each other in the tasks list.
</content>
		<task-remote-ids/>
	</task>

```

Here's another example with the "alternative IDs":

```xml
	<task id="0@1" status="Active" tags="" uuid="1990638b-4f95-4645-af3a-df1b27b35c10">
		<title>Getting Started With GTG</title>
		<addeddate>2020-04-10T20:48:21</addeddate>
		<modified>2020-04-10T20:48:11</modified>
		<subtask>1@1</subtask>
		<subtask>2@1</subtask>
		<subtask>3@1</subtask>
		<subtask>4@1</subtask>
		<subtask>5@1</subtask>
		<subtask>6@1</subtask>
		<subtask>7@1</subtask>
		<subtask>8@1</subtask>
		<content>
If you are interested in knowing more about GTG's other features, you will find more information here:
&lt;subtask&gt;2@1&lt;/subtask&gt;
&lt;subtask&gt;3@1&lt;/subtask&gt;
&lt;subtask&gt;4@1&lt;/subtask&gt;
&lt;subtask&gt;5@1&lt;/subtask&gt;
&lt;subtask&gt;6@1&lt;/subtask&gt;
&lt;subtask&gt;7@1&lt;/subtask&gt;
&lt;subtask&gt;8@1&lt;/subtask&gt;

The GTG team.</content>
		<task-remote-ids/>
	</task>


```

There are several problems here:

- Tasks have two IDs and it's not very clear when one or the other is used
- There are two ways to refer to a subtask, using one of the large IDs or using a textual representation
- The content of the content tag is escaped xml, like a matryoshka doll
- Tags are store by name in a stringified list
- Subtasks are referenced around by id twice. One in their proper tag, and then in content
- The file itself has no metadata about itself (like a version number or something)
- Tags are stored in a separate file

There's a projects.xml file which has some metadata and connects the tags xml with the tasks file. Apparently the previous team had envisioned something like a projects system, where tasks were contained in a project. Each project having it's own backend and associated tags file.

Looks like this was never completed though :thinking: 

## Proposed

- Put everything in one file. It can be called `gtg_data.xml` to avoid clashing with the old files.
- Use a single ID
- Use UUID4 for IDs
- Always use ISO 8601 for dates (except for fuzzy dates)
- Include a "header" section with metadata about the file
- Remove `task-remote-ids`. It's not being used at all, and some guy left a comment in the code saying he doesn't think we need them!

### Tags

- All tags are stored as long as they meet one of these conditions:
  1. They have at least one task
  2. They have some kind of customization (color/icon/etc)
- Tasks refer to tags by their UUID
- Tags in the content aren't marked (the text editor can find them easily)

This is what that task would look like:

```xml
<gtgData appVersion="0.5" xmlVersion="2">
	<taglist>
		<tag id="7171ff82-119a-4933-8277-a8ef5ce6a3e2" color="E9B96E" name="GTG"/>
		<tag id="140f74ea-b2f1-4b0f-b72b-0e85f471bb98" color="cdd3854e56d8" icon="emblem-shared-symbolic.symbolic" name="life"/>
		<tag id="94669f60-2f8e-4b16-b87f-c1d46ade4536" color="c96a52131cd2" name="errands"/>
		<tag id="46890bc2-c924-4146-8279-472099abc0b1" color="c96a52131cd2" name="other_errands"/>
		<tag id="aeb6e795-cb65-4d89-bf80-c7ea524fcfa7" color="c96a52131cd2" name="home_renovation"/>
	</taglist>

	<tasklist>
		<task id="2fdcd50f-0106-48b2-9f16-db2f8dbbf044" status="Active">
			<title>Learn How To Use Subtasks</title>
			<tags>
				<tag>7171ff82-119a-4933-8277-a8ef5ce6a3e2 <tag/>
				<tag>46890bc2-c924-4146-8279-472099abc0b1 <tag/>
				<tag>94669f60-2f8e-4b16-b87f-c1d46ade4536 <tag/>
			</tags>
			<dates>
				<addedDate>2020-04-10T20:48:11</addedDate>
				<modifyDate>2020-04-10T20:37:02</modifyDate>
				<startDate>2020-05-10T00:00:00</startDate>
			</dates>

			<content>
                            <p>@GTG, @errands, @home_renovation 
                             A &amp;quot;Subtask&amp;quot; is something that you need to do first before being able to accomplish your task. In GTG, the purpose of subtasks is to cut down a task in smaller subtasks that are easier to achieve and to track down.

			To insert a subtask in the task description (this window, for instance), begin a line with &amp;quot;-&amp;quot;, then write the subtask title and press Enter.

			Try inserting one subtask below. Type &amp;quot;- This is my first subtask!&amp;quot;, for instance, and press Enter:</p>

			<sub>bf33b248-ab96-4b99-9e40-8b60c1d7fe2e</sub>
			<sub>a957c32a-6293-46f7-a305-1caccdfbe34c</sub>
			<sub>98b683e0-1efa-4d8d-b3f9-8bcf954942d6</sub>

			<p>Alternatively, you can also use the &amp;quot;Insert Subtask&amp;quot; button.

			Note that subtasks obey to some rules: first, a subtask's due date can never happen after its parent's due date and, second, when you mark a parent task as done, its subtasks will also be marked as done.

			And if you are not happy with your current tasks/subtasks organization, you can always change it by drag-and-dropping tasks on each other in the tasks list.</p>
			</content>
                        </task>
	                <task id="bf33b248-ab96-4b99-9e40-8b60c1d7fe2e" status="Done">
				<title>One subtask</title>
				<content><p>This is some test subtask with a @tag </p></content>
			</task>

			<task id="a957c32a-6293-46f7-a305-1caccdfbe34c" status="Active">
				<title>Another subtask</title>
	   		       <dates>
				       <addedDate>2020-04-10T20:48:11</addedDate>
                                       <fuzzyDueDate>someday</fuzzyDueDate>			
			        </dates>
			        <content />
			</task>

				<!-- You get the point... -->
	</tasklist>
</gtgData>
```

## Versioning

We should always keep support for n-1 versions. This could go into `versioning` module. Since we have different filenames we can try to read `gtg_data.xml` first, if it's not there we can try to detect `projects.xml` and go into the versioning code.

---

Feedback much appreciated!

### PR DESCRIPTION
**Pull request by diegogangl**
This is a branch for the new file format based on a spec from #279 with help from @johnnybubonic.
The spec is documented here: https://github.com/getting-things-gnome/gtg/blob/file_format_2/docs/contributors/file%20format.md

Testing super appreciated! GTG makes tons of backups, but this should still be as rock solid as possible.

closes #279 

## How to test:

Basically open GTG dev and play around. See if anything is saved incorrectly or there are any weird errors.
Another option is to use the import scripts from the `scripts` folder. You can import your tasks from GTG stable and test with them.

### CODE REVIEW

**Comment by nekohayo** [comment]
On trying to launch with my personal dataset on the file_format_2 branch on my Ubuntu GTG smoke testing machine, while having previously launched it under master, I get this traceback preventing startup (and the process hangs there, you have to kill it):

```
2021-01-19 10:29:22,811 - DEBUG - application:set_debug_flag:580 - Debug output enabled.
2021-01-19 10:29:22,881 - DEBUG - __init__:__init__:58 - Backends found: ['backend_localfile', 'backend_signals']
2021-01-19 10:29:23,089 - WARNING - backend_localfile:this_is_the_first_run:147 - Found old file. Running versioning code.
Traceback (most recent call last):
  File "/home/user/gtg/.local_build/install/lib/python3.8/site-packages/GTG/gtk/application.py", line 95, in do_startup
    for backend_dic in BackendFactory().get_saved_backends_list():
  File "/home/user/gtg/.local_build/install/lib/python3.8/site-packages/GTG/backends/__init__.py", line 167, in get_saved_backends_list
    dic["backend"].this_is_the_first_run(None)
  File "/home/user/gtg/.local_build/install/lib/python3.8/site-packages/GTG/backends/backend_localfile.py", line 149, in this_is_the_first_run
    tree = versioning.convert(old_path, self.datastore)
AttributeError: 'Backend' object has no attribute 'datastore'
Traceback (most recent call last):
  File "/home/user/gtg/.local_build/install/lib/python3.8/site-packages/GTG/gtk/application.py", line 122, in do_activate
    self.init_shared()
  File "/home/user/gtg/.local_build/install/lib/python3.8/site-packages/GTG/gtk/application.py", line 158, in init_shared
    self.init_browser()
  File "/home/user/gtg/.local_build/install/lib/python3.8/site-packages/GTG/gtk/application.py", line 166, in init_browser
    self.browser = MainWindow(self.req, self)
  File "/home/user/gtg/.local_build/install/lib/python3.8/site-packages/GTG/gtk/browser/main_window.py", line 69, in __init__
    self.config = self.req.get_config('browser')
AttributeError: 'NoneType' object has no attribute 'get_config'
```

**Comment by diegogangl** [comment]
Can't replicate. Maybe it's a race condition (`register_datastore()` hasn't been called yet)?

**Comment by Neui** [comment]
I was able to reproduce. Looking at it, `self.datastore` is not set. This is set by `GenericBackend.register_datastore` which is called part of the `TaskSource.__init__`, which is only constructed in `DataStore.register_backend`, which is only called in `Application.do_startup` inside the loop. However, `this_is_the_first_run` is only called inside the `BackendFactory.get_saved_backends_list`, which is called before that loop body runs.

In my case, the loop before calling `this_is_the_first_run` (`for backend in config.get_all_backends():`), `config.get_all_backends()` returns nothing since the `backends.conf` config file either doesn't exists or is is empty.

I don't know how it would work for you.

**Comment by diegogangl** [comment]
Deleting `backends.conf` and `gtg_data.xml` (if present) triggers the bug

**Comment by diegogangl** [comment]
Pushed a fix for that bug

**Comment by nekohayo** [comment]
Now it launches, but with my personal data set (anonymized version) auto-imported/converted by your implementation:
* Tags and subtasks are not shown at all inside the task editor, only the title and description are shown
* The tasks/subtasks hierarchy is completely gone from the task browser's list of tasks, for any given tag
* projects.xml is somehow not updated to point to the new gtg_data.xml file but still works? Is this branch doing away entirely with the notion of projects (aka profiles), which may have been interesting for the future?

**Comment by diegogangl** [comment]
> projects.xml is somehow not updated to point to the new gtg_data.xml file but still works? Is this branch doing away entirely with the notion of projects (aka profiles), which may have been interesting for the future?


This was mentioned in #279. We don't really need another xml file since everything is inside `gtg_data.xml`. You can have different profiles by loading different xml files directly.

**Comment by tkdchen** [comment]
Synced the code and the latest one on master branch is fa7b34ab.

After `./launch.sh`, the gtg dialog is empty. My tasks are still available in `tmp/default/xdg/data/gtg/gtg_tasks.xml`.

Do I have to run `scripts/import_my_tasks_into_debug_tasks.sh` to import the data into the new format?

I gave a try to run the script and got:

```
Running the development/debug version - using separate user directories
Your data is in the 'tmp' subdirectory with the 'default' dataset.
-----------------------------------------------------------------------
cp: cannot stat '/home/chen/.local/share/gtg/*': No such file or directory
cp: cannot stat '/home/chen/.config/gtg/*': No such file or directory
```

What prerequisite is required to run the script?

**Comment by morhe-blip** [comment]
Confirmed in https://github.com/getting-things-gnome/gtg/issues/565

If you work with the dev version (as I do), the script should not work, because there is no data .local/ folder.
This folder is used for the 'regular' version of GTG.

**Comment by WhilelM** [comment]
Same problem that @tkdchen 
Synced the code and the latest one on master branch is 4a608d25d09374dff3e76644095557f4b67e69b1
After ./launch.sh, the gtg dialog is empty. My tasks are still available in tmp/default/xdg/data/gtg/f4cf1957-8b10-4562-917b-812e5e170377.xml

I could work with my data when checkout commit 5442868d9d78a598dfc3d856e73039214e1306c4

**Comment by diegogangl** [comment]
@WhilelM is this data from older versions of GTG (0.3 and earlier)? Could you try renaming that file to `gtg_tasks.xml`?

**Comment by WhilelM** [comment]
> @WhilelM is this data from older versions of GTG (0.3 and earlier)? Could you try renaming that file to `gtg_tasks.xml`?

I have backup from 2013 and I use debian, so I think so.
I tried `git checkout master` and copied in a new file `cp tmp/default/xdg/data/gtg/f4cf1957-8b10-4562-917b-812e5e170377.xml tmp/default/xdg/data/gtg/gtg_tasks.xml`. no more success =/

**Comment by WhilelM** [comment]
How can I convert my data to new format ?

**Comment by diegogangl** [comment]
HI @WhilelM, it should convert automatically. Try using master, not this branch though.

**Comment by WhilelM** [comment]
I still have issue with my data. I'm stucked with commit 5442868d9d78a598dfc3d856e73039214e1306c4 and can't load any task if I use anything less older.
How gtg would convert it automatically ?

**Comment by diegogangl** [comment]
That's weird, there's no change in the file format there or in any recent commit. Are you getting any errors in the terminal?

**Pull request merged**
