### PR TITLE
adding dbus as dependency to hamster plugin.

### PR DESCRIPTION
**Pull request by flavin**
ref #492

### CODE REVIEW

**Comment by Neui** [comment]
AFAIK @diegogangl wanted to drop dbus-python in favour of the Gio(/GLib) DBus implementation, like the [project page suggests](https://dbus.freedesktop.org/doc/dbus-python/).
Since this is an plugin, this might not be too "critical", but maybe keep in mind that the plugin maybe could be migrated to Gio.

> @Neui can you check this PR #497 to avoid appending once and once again dbus

I can confirm. This would fix #492.
(But I can't activate it (checkbox just doesn't check, and there is an user-unfriendly traceback about not being able to find the hamster dbus thing (reasonable since I don't use it)) and trying to access the plugin settings also throws an traceback; But I would consider out of scope for this PR)

**Comment by diegogangl** [comment]
Hi @flavin, thanks for jumping on this. I'm sorta in favor of merging this. Honestly the best solution is to port to Gio.dbus and get rid of pydbus altogether. But if it's too difficult, we could merge this and release 0.5 as it is.

**Comment by flavin** [comment]
@Neui @diegogangl  it makes all the sense migrate plugins too to Gio, and apart of migrate plugins to use it gio.dbus, we also will need something like this without pydbus https://github.com/getting-things-gnome/gtg/commit/931427b1d9f1d00c3b7ee6210802b7f9b01349c1 or give the responsability to plugin to handle their dbus dependency

**Comment by diegogangl** [comment]
Yeah, we could bring that method back using Gio. We just need to remember to poke holes in the sandbox for each dbus interface we need to access, otherwise that method will always fail under flatpak. 
(which reminds me I need to poke a hole for Hamster)

**Comment by diegogangl** [comment]
Let's go ahead and merge this PR as it is, so we can get 0.5 out soon. We can do the port afterwards :+1:

**Pull request merged**
