### PR TITLE
Detect selected pane as fallback for selection

### LINKED ISSUE #168: Wrong task being opened from the workview tab
Sometimes if I switch to the workview tab and open some task another one will be opened instead.

You can reproduce this bug with the following procedure:
1. Start with a clean profile (remove `~/.config/gtg` and `~/.local/share/gtg`; make a backup first!)
2. Remove "Learn How to Use Subtasks" from the Active Tasks tab
3. Switch to the Workview tab
4. Open "Learn How to Use Plugins"

Result: "Learn How To Use Synchronization Services" is opened instead.

Edit: I'm using gtg-git version r5170.a795d66-1 from Parabola GNU/Linux-libre (an Arch Linux derivative distribution).

### PR DESCRIPTION
**Pull request by diegogangl**
This PR fixes the wrong tasks being deleted from the closed view

Also fixes #168

### CODE REVIEW

**Comment by diegogangl** [comment]
Lol, how did that end up inside the docstring?

> Otherwise, I really appreciate your contributions. It's very welcome. I'm not on IRC but if you want, I would be glad to answer your questions or guide you through the code, by email, IM or even video chat.

Thanks! I'll probably drop you a line next time I get stuck :)

**Comment by ploum** [comment]
shouldn't that one be rebased too ?

**Comment by diegogangl** [comment]
mmmh wait, why is that merge from master in this branch? it mentions the other branch

**Comment by ploum** [comment]
mmm, github is asking me to rebase and merge all your PR. I have no idea why. I may have accepted one previously but it's strange.

**Comment by nekohayo** [comment]
Not totally clear to me if this still has something pending or if all the related commits/code were merged into master after all? If so @diegogangl can close this and issue #116 :)

**Pull request merged**
