### PR TITLE
readme: Remove outdated and obsolete build status badge

### PR DESCRIPTION
**Pull request by picsel2**
Update build status badge to use the github workflow and move it more towards the top.

### CODE REVIEW

**Comment by Neui** [comment]
I think it can either be after the social media badges or on a new line below the other badges, since that beginning section is primary information including normal users, so I don't think it is "important" for normal users to know the tests state.

Also I am not sure if even need such badge at all, since GitHub already has such feature next to the commit (and below PRs), and is visible without scrolling (I almost never look at the README if I am not a user).

**Comment by picsel2** [comment]
I've updated the PR to remove the obsolete badge completely.

**Comment by wieslawmlynarski** [comment]
What about just replacing it with something like this

`
[Unit Tests](https://github.com/getting-things-gnome/gtg/actions/workflows/unit_tests.yml)
`

[Unit Tests](https://github.com/getting-things-gnome/gtg/actions/workflows/unit_tests.yml)

**Comment by diegogangl** [comment]
I think deleting it is the best way to go, thoughts on this @nekohayo ?

**Comment by diegogangl** [comment]
Merged, thanks!

**Pull request merged**
