### PR TITLE
Show as enabled delete context menu in closed task

### LINKED ISSUE #405: "Delete" action in the right-click contextual menu is disabled (insensitive) in the Closed tasks view
This action still works if you use the keyboard shortcut (Ctrl+Delete), it's just not activatable via the right-click menu while inside the "Closed" tasks view mode. It is available and working while in other (Open, Actionable) view modes.

### PR DESCRIPTION
**Pull request by flavin**
the logic was working and for example shortcut works, but the menu was disabled.
here we enable the logic for closed tasks.
close #405

### CODE REVIEW

**Comment by flavin** [comment]
@nekohayo  @diegogangl  please review

**Comment by diegogangl** [comment]
Hi @flavin, I'm currently having some health issue in my family and I'm spending pretty much the entire day in the hospital. The rest of the time I'm trying to keep up with freelance work + eating + sleeping. 

I think @nekohayo is also pretty tied up with work. I'm not sure when we'll able to review this.
Hoping to get back soon(ish?) though!

**Comment by flavin** [comment]
> Hi @flavin, I'm currently having some health issue in my family and I'm spending pretty much the entire day in the hospital. The rest of the time I'm trying to keep up with freelance work + eating + sleeping.
oh I hope everything goes well diego.

**Comment by diegogangl** [comment]
Thanks, he's slowly getting better. They will probably move him back to a regular room tommorrow.
Thanks for the work too!

**Pull request merged**
