### PR TITLE
Added strftime to Date

### LINKED ISSUE #870: AttributeError traceback when trying to open a particular recurring task: 'Date' object has no attribute 'strftime'
I don't know if this would happen with the git version and the new core, but in case this is useful, here's a traceback I encountered on 0.6 today when trying to open/edit my recurring "treat the leather clothes" task:

```python-traceback
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/GTG/gtk/browser/main_window.py", line 1060, in on_edit_active_task
    self.app.open_task(tid)
  File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line 553, in open_task
    editor = TaskEditor(requester=self.req, app=self, task=task,
  File "/app/lib/python3.9/site-packages/GTG/gtk/editor/editor.py", line 98, in __init__
    self.recurring_menu = RecurringMenu(self.req, task.tid, self.builder)
  File "/app/lib/python3.9/site-packages/GTG/gtk/editor/recurring_menu.py", line 45, in __init__
    self.update_header()
  File "/app/lib/python3.9/site-packages/GTG/gtk/editor/recurring_menu.py", line 121, in update_header
    month_day=self.task.get_recurring_updated_date().strftime('%d')))
AttributeError: 'Date' object has no attribute 'strftime'
```

The offending task looks like this in my `gtg_data.xml` file:

```
    <task id="ec4435e2-63de-4481-8d6a-bbea84e46562" status="Dismiss" uuid="ec4435e2-63de-4481-8d6a-bbea84e46562" recurring="True">
      <tags>
        <tag>a0261164-c489-4032-9942-7c5cecb6e3dd</tag>
      </tags>
      <title>conditionner les vêtements de cuir</title>
      <dates>
        <added>2022-01-15T14:24:39.347643</added>
        <modified>2022-03-03 09:41:19.407247</modified>
        <done>2022-03-03</done>
        <due>2022-02-21</due>
        <start>2022-03-03</start>
      </dates>
      <recurring enabled="true">
        <term>month</term>
        <updated_date>2022-01-15T14:24:39.359351</updated_date>
      </recurring>
      <subtasks/>
      <content><![CDATA[1x/quarter si inutilisés, monthly si légèrement utilisés; simply use cream sur toutes les paires de souliers! cf notes @apparte]]></content>
    </task>
```

### PR DESCRIPTION
**Pull request by APCBoston**
Fixes #870 
#942 arose during testing but does not appear to be created by/related to this patch (or, for that matter, reproducible)

### CODE REVIEW

**Comment by APCBoston** [comment]
Reopening as this was closed in error.

**Comment by APCBoston** [comment]
How exciting that the megaport is done!  I'll do the rebase now.

**Comment by APCBoston** [comment]
Looking at the GH Actions for the repo, it appears that automated unit testing is currently broken?  The test failure doesn't appear directly related to the code in this PR.

**Comment by nekohayo** [comment]
Indeed, see also #999 ;)

**Comment by diegogangl** [comment]
Sorry for long delay @APCBoston! This LGTM, it doesn't conflict with anything in the megabranch and it adds some functionality to the Date class. 
Thanks! Merging

**Pull request merged**
