### PR TITLE
Fix appdata related issues

### PR DESCRIPTION
**Pull request by yakushabb**
- Add missing developer block
- Update homepage to github page, due to the wiki page are going to be retired.
- Add vcs-browser URL
- Update translation URL
- Remove the none aors rules
- Fix the updatecontact tag
- Copy screenshots to the repository

### CODE REVIEW

**Comment by yakushabb** [comment]
GNOME wiki pages are going to be retired. 

Old screenshots links seem not working.

resim

resim

**Comment by diegogangl** [comment]
Yes, but we could put them in this repo's wiki:
https://github.blog/changelog/2022-02-14-upload-images-to-wiki-pages/

**Comment by yakushabb** [comment]
If you kindly provide URLs, I can update them. It seems that 'gtg' does not have a wiki page on GitHub.

**Comment by diegogangl** [comment]
While trying it, it seems we can't control the urls of the images we post. I wonder if @nekohayo would mind hosting the images? Otherwise we can put them in git lfs

**Comment by Neui** [comment]
You can clone a git wiki repo on the wiki page, does commiting images there and pushing them work?

**Comment by yakushabb** [comment]
I really have no idea how to commit a wiki page on GitHub. 

I suppose providing an image URL should work for AppData.

**Comment by diegogangl** [comment]
Thanks for tip @Neui !
@yakushabb Sorry for the wait, here are the urls:

```
https://raw.githubusercontent.com/wiki/getting-things-gnome/gtg/assets/screenshots/0.6/main_with_background.png
https://raw.githubusercontent.com/wiki/getting-things-gnome/gtg/assets/screenshots/0.6/main_window.png
https://raw.githubusercontent.com/wiki/getting-things-gnome/gtg/assets/screenshots/0.6/detail.png
```

**Comment by yakushabb** [comment]
Updated.

**Comment by diegogangl** [comment]
...and merged! 
Thanks for the work :)

**Pull request merged**
