### PR TITLE
Proposal for schema

### PR DESCRIPTION
**Pull request by johnnybubonic**
Hey all! I'm composing some [XSDs](https://www.w3.org/TR/xmlschema-1/) for GTG.

## Why?

This, combined with the porting to LXML (#401) (LXML natively supports XSD), will let you do some REALLY nice things programmatically:

* Automatic data validation/verification
* Automatic structure validation/verification
* Automatic population of default attributes
* Address and enforce concerns in #279 as they're implemented
* *Very* easy test cases for generated XML

## Review

I'd like someone more familiar with the GTG guts to give it a look over. Please review and reference the items marked:

```xml
<!--
  TODO: ...
-->
```
for specific questions/concerns/suggestions I have.

## Outer scope changes

The gtg_tasks.xml, etc. may need to have namespaces added.

e.g. for `gtg_tasks.xml`, instead of:

```xml
<?xml version="1.0" ?>
<project>
<!-- ... -->
</project>
```

it'd be:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="https://wiki.gnome.org/Apps/GTG?tasks"
         xsi:schemaLocation="http://SOMEDOMAIN.TLD/SOME/PATH/TO/tasks.xsd">
<!-- ... -->
</project>
```

This can be done programmatically, and I can provide code to convert existing documents over to the namespaced version.

## Implementation

I can provide examples of how to automatically detect, parse, fetch, and validate XSDs (and strip the namespace once the data/structure is validated/verified and defaults are applied, so the elements don't need to be referenced by namespace) with lxml, as I have direct experience with lxml in python3 and the above.

### CODE REVIEW

**Comment by johnnybubonic** [comment]
Also mentioning @diegogangl on this since I get the impression he's doing a lot of the LXML porting.

**Comment by diegogangl** [comment]
While I really like the idea of having a schema, wouldn't it be better to wait for the new file format? We would end up doing this twice in the end.

**Comment by johnnybubonic** [comment]
yep, it would definitely be better. heh whoops. :)

any suggestions for issues/PR #'s to watch besides #279 ? i can happily write the schemas (i kind of enjoy it, to be honest), all i need to know is structure and what types of data/valid strings to accept. i can probably pick/make the proper datatypes and container types etc. from there.

**Comment by diegogangl** [comment]
Sure, #169 will also include some changes to the xml to support repeatable tasks.

**Comment by johnnybubonic** [comment]
Closed to switch branches.

**Pull request closed without merging**
