### PR TITLE
Shellcheck fixes

### PR DESCRIPTION
**Pull request by asadana**
Minor cleanup of the shell scripts to fix common shellcheck warnings and errors

### CODE REVIEW

**Comment by asadana** [comment]
While not listed in #237, this should help with Clean Up section of the issue

**Comment by asadana** [comment]
I see the problem. Sorry about that, fix coming up

**Comment by asadana** [comment]
@diegogangl 

There is currently `yes` command piped to `cp`. This is not necessary in the modern versions of `cp`, shellcheck throws a warning for this, but I haven't changed it incase this was put in for a purpose. Please let me know if you want these removed.

```sh
yes|cp -Rf ~/.local/share/gtg/* tmp/default/xdg/data/gtg/
yes|cp -Rf ~/.config/gtg/* tmp/default/xdg/config/gtg/
```

**Comment by diegogangl** [comment]
Indeed, cp doesn't read stdin. Yeah, it'd be nice to remove those too.
About debug.sh: it doesn't look like arguments are being passed to gtg at the end. You can try this by passing `-d`. You should see a ton of log messages and a gear icon in the window headerbar

**Comment by asadana** [comment]
> Indeed, cp doesn't read stdin. Yeah, it'd be nice to remove those too.
> About debug.sh: it doesn't look like arguments are being passed to gtg at the end. You can try this by passing `-d`. You should see a ton of log messages and a gear icon in the window headerbar

I reverted the commit to see what I was missing since I made sure the title was working yesterday.
It seems double-quoting of `args` in debug script messes up python argument flags besides explicitly specified `-t`.

I have fixed and tested `-d` flag. This required me to disable shellcheck for that specific launcher line (commented with informational message for future contributors)

I have also removed the `yes` pipe before `cp` command.

**Pull request merged**
