### PR TITLE
Swedish translation

### PR DESCRIPTION
**Pull request by ojn**
I will ask for correction-reading on our translators email list,
some small fixes might come from others

### CODE REVIEW

**Comment by diegogangl** [comment]
Hi @ojn, thanks for working on this! Let me know when this branch is ready to be merged

**Comment by ojn** [comment]
I have added some corrections, thanks goes to Tomas. I think it should be usable now.

**Comment by diegogangl** [comment]
Hey @ojn , translations look good but seems like a few of master's commit sneaked into this branch, and they are causing conflicts.

To make this mergeable we need to remove everything between 1cffb7d6022af17b118d8239fb7300e9e62d4b1d and 7b28cc20f1efba388b64238dcd2153a5b19e1145
(check out the commits tab)

**Comment by ojn** [comment]
@diegogangl 

> seems like a few of master's commit sneaked into this branch, and they are causing conflicts.

oh, I confused the workflow somehow, hopefully should be good now

**Comment by diegogangl** [comment]
Merged, thanks!

**Pull request merged**
