### PR TITLE
Use Gtk.MessageDialog for the task delete dialog

### PR DESCRIPTION
**Pull request by diegogangl**
This technically fixes the missing icon issue because these dialogs don't use icons anymore.

Screenshot from 2019-12-21 21-15-12

### CODE REVIEW

**Comment by ploum** [comment]
Hi,

Could you update your trunk and rebase your merge ?

**Comment by diegogangl** [comment]
Hi, this is up to date with master. What conflicts are you getting?

**Comment by ploum** [comment]
Screenshot 2019-12-23 at 18 37 36

Not sure what it means.

**Comment by diegogangl** [comment]
Did it look different before? seems like that's the usual way for github:
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges#rebase-and-merge-your-pull-request-commits

It means there are no conflicts and it can be rebased and merged automatically.
The yellow part is the is CI which is apparently not done checking. It doesn't seem to be working TBH.
It's still "checking" the other branch from 10 days ago

**Comment by diegogangl** [comment]
Hi, looks like something went wrong with the merging? The commit in the middle says fix_delete_dialog but includes the same changes from the previous (from detect pane)

Screenshot from 2019-12-23 21-31-32

**Pull request merged**
